"""
Upgrade bot_exploration_3b.ipynb — All fixes:
1. Pass MAX_NEW_TOKENS/TEMPERATURE through to LLMClient
2. Cache LLM per model (load once, reuse across conditions)
3. Per-episode token/time deltas instead of cumulative
4. Full-grid scan in get_text_obs (keys, doors, boxes, lava)
5. Fallback target for envs with no goal tile (BlockedUnlockPickup)
6. Viz cell groups by buffer_size
+ Previous: new templates, buffer_size sweep, action logging
"""
import json
from pathlib import Path

nb_path = Path("bot_exploration.ipynb")
with open(nb_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

cells = nb["cells"]

# ── 0. IMPORTS CELL (id: 28b6b696) — Add seaborn ─────────────────────
for cell in cells:
    if cell.get("id") == "28b6b696":
        src = "".join(cell["source"])
        if "seaborn" not in src:
            src += "import seaborn as sns\n"
            cell["source"] = [src]
            cell["outputs"] = []
            print("  [patched] imports: added seaborn")
        break

# ── 1. CONFIG CELL ─────────────────────────────────────────────────────
for cell in cells:
    src = "".join(cell.get("source", []))
    if "MODEL_CANDIDATES" in src and "MAX_NEW_TOKENS" in src:
        cell["source"] = [
            "MODEL_CANDIDATES = [\n",
            '    "Qwen/Qwen2.5-3B-Instruct",\n',
            '    "Qwen/Qwen2.5-7B-Instruct",\n',
            "]\n",
            "MAX_NEW_TOKENS = 16\n",
            "TEMPERATURE = 0.0\n",
            "MOCK_MODE = False\n",
            "HISTORY_WINDOWS = (1, 2, 3)\n",
            "ENVIRONMENTS = [\n",
            '    "MiniGrid-LavaGapS7-v0",\n',
            '    "MiniGrid-BlockedUnlockPickup-v0",\n',
            '    "MiniGrid-DoorKey-5x5-v0",\n',
            '    "MiniGrid-Empty-8x8-v0",\n',
            "]\n",
            "N_EPISODES_LIST = (10,)\n",
            "MAX_STEPS_LIST = (50,)\n",
            "BUFFER_SIZES = (2, 5)\n",
            'OUTPUT_ROOT = "CS 228/outputs"\n',
            'RUN_TAG = "bot_sweep"\n',
        ]
        cell["outputs"] = []
        break

# ── 2. BOT ARCH CELL (id: bot_arch) ───────────────────────────────────
for cell in cells:
    if cell.get("id") == "bot_arch":
        cell["source"] = [
            "from dataclasses import dataclass\n",
            "\n",
            "@dataclass\n",
            "class ThoughtTemplate:\n",
            "    name: str\n",
            "    description: str\n",
            "    reasoning_pattern: str\n",
            "    usage_count: int = 0\n",
            "    success_rate: float = 0.0\n",
            "\n",
            "ALL_TEMPLATES = [\n",
            "    ThoughtTemplate(\n",
            '        name="Direct Navigation",\n',
            '        description="Moving towards a visible target in an empty space.",\n',
            '        reasoning_pattern="1. Locate target coordinates. 2. Identify relative direction. 3. Align orientation. 4. Move forward.",\n',
            "    ),\n",
            "    ThoughtTemplate(\n",
            '        name="Obstacle Avoidance",\n',
            '        description="Navigating around walls, lava, or closed doors.",\n',
            '        reasoning_pattern="1. Identify blocking object. 2. Scan for open path. 3. Plan detour. 4. Execute lateral move.",\n',
            "    ),\n",
            "    ThoughtTemplate(\n",
            '        name="Object Acquisition",\n',
            '        description="Locating and picking up a key or other inventory item.",\n',
            '        reasoning_pattern="1. Scan grid for target object (key/ball). 2. Navigate to the object. 3. Face the object. 4. Use pickup action.",\n',
            "    ),\n",
            "    ThoughtTemplate(\n",
            '        name="Unlock Door",\n',
            '        description="Using a held key to open a locked door.",\n',
            '        reasoning_pattern="1. Confirm key is in inventory. 2. Navigate to the locked door. 3. Face the door. 4. Use toggle action to unlock and open.",\n',
            "    ),\n",
            "    ThoughtTemplate(\n",
            '        name="Clear Path",\n',
            '        description="Moving blocking objects out of the way to reach a target.",\n',
            '        reasoning_pattern="1. Identify the blocking object. 2. Face the blocker. 3. Pickup or push the blocker aside. 4. Drop it in a clear cell. 5. Return to original objective.",\n',
            "    ),\n",
            "]\n",
            "\n",
            "class MetaBuffer:\n",
            "    def __init__(self, buffer_size=2):\n",
            "        self.templates = {}\n",
            "        self._initialize_templates(buffer_size)\n",
            "\n",
            "    def _initialize_templates(self, buffer_size):\n",
            "        for t in ALL_TEMPLATES[:buffer_size]:\n",
            "            self.add_template(t)\n",
            "\n",
            "    def add_template(self, template: ThoughtTemplate):\n",
            "        self.templates[template.name] = template\n",
            "\n",
            "    def retrieve(self, problem_description: str) -> ThoughtTemplate:\n",
            "        desc = problem_description.lower()\n",
            '        if "Clear Path" in self.templates and ("box" in desc or "ball" in desc):\n',
            '            return self.templates["Clear Path"]\n',
            '        if "Object Acquisition" in self.templates and "key" in desc:\n',
            '            return self.templates["Object Acquisition"]\n',
            '        if "Unlock Door" in self.templates and "door" in desc:\n',
            '            return self.templates["Unlock Door"]\n',
            '        if "wall" in desc or "lava" in desc or "door" in desc:\n',
            '            if "Obstacle Avoidance" in self.templates:\n',
            '                return self.templates["Obstacle Avoidance"]\n',
            '        return self.templates["Direct Navigation"]\n',
            "\n",
            "class ProblemDistiller:\n",
            "    @staticmethod\n",
            "    def distill(obs_text: str) -> str:\n",
            "        return obs_text\n",
            "\n",
            "class BufferManager:\n",
            "    def __init__(self, buffer_size=2):\n",
            "        self.meta_buffer = MetaBuffer(buffer_size=buffer_size)\n",
            "        self.thought_history = deque(maxlen=50)\n",
            "\n",
            "    def get_reasoning_aid(self, distilled_problem: str) -> str:\n",
            "        template = self.meta_buffer.retrieve(distilled_problem)\n",
            '        return f"[TEMPLATE: {template.name}]\\n{template.reasoning_pattern}"\n',
        ]
        cell["outputs"] = []
        break

# ── 3. WRAPPER CELL (id: wrapper_code) — Bugs 4 & 5 ──────────────────
for cell in cells:
    if cell.get("id") == "wrapper_code":
        cell["source"] = [
            "class MinigridTextWrapper:\n",
            "    def __init__(self, env_id, render_mode=None):\n",
            "        self.env = gym.make(env_id, render_mode=render_mode)\n",
            "        self.env = FullyObsWrapper(self.env)\n",
            "        self.action_map = {\n",
            '            "turn_left": Actions.left,\n',
            '            "turn_right": Actions.right,\n',
            '            "forward": Actions.forward,\n',
            '            "pickup": Actions.pickup,\n',
            '            "drop": Actions.drop,\n',
            '            "toggle": Actions.toggle,\n',
            '            "done": Actions.done\n',
            "        }\n",
            "\n",
            "    def _base_env(self):\n",
            "        return self.env.unwrapped\n",
            "\n",
            "    def _find_goal_pos(self):\n",
            "        base = self._base_env()\n",
            "        grid = base.grid\n",
            "        for x in range(grid.width):\n",
            "            for y in range(grid.height):\n",
            "                cell = grid.get(x, y)\n",
            '                if cell is not None and getattr(cell, "type", None) == "goal":\n',
            "                    return (int(x), int(y))\n",
            "        return None\n",
            "\n",
            "    def _scan_grid_objects(self):\n",
            '        """Scan the full grid for notable objects and their positions."""\n',
            "        base = self._base_env()\n",
            "        grid = base.grid\n",
            "        objects = []\n",
            "        for x in range(grid.width):\n",
            "            for y in range(grid.height):\n",
            "                cell = grid.get(x, y)\n",
            "                if cell is None:\n",
            "                    continue\n",
            "                obj_type = getattr(cell, 'type', None)\n",
            '                if obj_type in ("key", "door", "box", "ball", "lava"):\n',
            "                    state = \"\"\n",
            '                    if obj_type == "door":\n',
            "                        if getattr(cell, 'is_locked', False):\n",
            '                            state = " (locked)"\n',
            "                        elif getattr(cell, 'is_open', False):\n",
            '                            state = " (open)"\n',
            "                        else:\n",
            '                            state = " (closed)"\n',
            '                    color = getattr(cell, "color", "")\n',
            '                    label = f"{color} {obj_type}".strip() if color else obj_type\n',
            "                    objects.append(f\"{label}{state} at [{x}, {y}]\")\n",
            "        return objects\n",
            "\n",
            "    def _find_fallback_target(self):\n",
            '        """For envs with no goal tile, find a box or ball as target."""\n',
            "        base = self._base_env()\n",
            "        grid = base.grid\n",
            "        for x in range(grid.width):\n",
            "            for y in range(grid.height):\n",
            "                cell = grid.get(x, y)\n",
            '                if cell is not None and getattr(cell, "type", None) in ("box", "ball"):\n',
            "                    return (int(x), int(y)), getattr(cell, 'type', 'box')\n",
            "        return None, None\n",
            "\n",
            "    def get_text_obs(self, obs):\n",
            "        base = self._base_env()\n",
            "\n",
            '        if hasattr(base, "agent_pos") and base.agent_pos is not None:\n',
            "            ax, ay = int(base.agent_pos[0]), int(base.agent_pos[1])\n",
            '            agent_pos_text = f"[{ax}, {ay}]"\n',
            "        else:\n",
            '            agent_pos_text = "None"\n',
            "\n",
            '        agent_dir = int(base.agent_dir) if hasattr(base, "agent_dir") else None\n',
            "        goal_pos = self._find_goal_pos()\n",
            "\n",
            "        if goal_pos is not None:\n",
            '            target_text = f"Goal is at [{goal_pos[0]}, {goal_pos[1]}]."\n',
            "        else:\n",
            "            fallback_pos, fallback_type = self._find_fallback_target()\n",
            "            if fallback_pos is not None:\n",
            '                target_text = f"Target ({fallback_type}) is at [{fallback_pos[0]}, {fallback_pos[1]}]."\n',
            "            else:\n",
            '                target_text = "No target found."\n',
            "\n",
            '        dirs = ["right", "down", "left", "up"]\n',
            '        facing = dirs[agent_dir] if agent_dir is not None and 0 <= agent_dir < 4 else "unknown"\n',
            '        desc = f"Agent is at {agent_pos_text} facing {facing}. {target_text}"\n',
            "\n",
            "        front_obj = None\n",
            '        if hasattr(base, "front_pos") and hasattr(base, "grid"):\n',
            "            fx, fy = int(base.front_pos[0]), int(base.front_pos[1])\n",
            "            front_obj = base.grid.get(fx, fy)\n",
            "\n",
            "        if front_obj:\n",
            '            desc += f" In front of you is a {front_obj.type}."\n',
            "        else:\n",
            '            desc += " The path in front is clear."\n',
            "\n",
            "        grid_objects = self._scan_grid_objects()\n",
            "        if grid_objects:\n",
            '            desc += " Nearby objects: " + ", ".join(grid_objects) + "."\n',
            "\n",
            "        return desc\n",
            "\n",
            "    def reset(self):\n",
            "        reset_out = self.env.reset()\n",
            "        if isinstance(reset_out, tuple) and len(reset_out) == 2:\n",
            "            obs, _ = reset_out\n",
            "        else:\n",
            "            obs = reset_out\n",
            "        return self.get_text_obs(obs)\n",
            "\n",
            "    def step(self, action_str):\n",
            "        action = self.action_map.get(action_str.lower(), Actions.forward)\n",
            "        obs, reward, terminated, truncated, info = self.env.step(action)\n",
            "        done = terminated or truncated\n",
            "        return self.get_text_obs(obs), reward, done, info\n",
        ]
        cell["outputs"] = []
        break

# ── 3b. LLM CELL (id: llm_code) — Fix mock for new target format ─────
for cell in cells:
    if cell.get("id") == "llm_code":
        src = "".join(cell["source"])
        # Replace _extract_state_from_prompt to also match "Target (...) is at [x, y]"
        old_extract = '''    @staticmethod
    def _extract_state_from_prompt(prompt):
        import re

        coord_pat = r"[\\[\\(]\\s*(\\d+)\\s*,\\s*(\\d+)\\s*[\\]\\)]"
        pos_match = re.search(rf"Agent is at {coord_pat} facing (\\w+)", prompt)
        goal_match = re.search(rf"Goal is at {coord_pat}", prompt)

        if not pos_match or not goal_match:
            return None

        ax, ay = int(pos_match.group(1)), int(pos_match.group(2))
        face = pos_match.group(3)
        gx, gy = int(goal_match.group(1)), int(goal_match.group(2))
        return ax, ay, face, gx, gy'''

        new_extract = '''    @staticmethod
    def _extract_state_from_prompt(prompt):
        import re

        coord_pat = r"[\\[\\(]\\s*(\\d+)\\s*,\\s*(\\d+)\\s*[\\]\\)]"
        pos_match = re.search(rf"Agent is at {coord_pat} facing (\\w+)", prompt)
        goal_match = re.search(rf"Goal is at {coord_pat}", prompt)
        if goal_match is None:
            goal_match = re.search(rf"Target \\(\\w+\\) is at {coord_pat}", prompt)

        if not pos_match or not goal_match:
            return None

        ax, ay = int(pos_match.group(1)), int(pos_match.group(2))
        face = pos_match.group(3)
        gx, gy = int(goal_match.group(1)), int(goal_match.group(2))
        return ax, ay, face, gx, gy'''

        if old_extract in src:
            src = src.replace(old_extract, new_extract)
            cell["source"] = [src]
            cell["outputs"] = []
            print("  [patched] _extract_state_from_prompt: now matches 'Target (box) is at' too")
        else:
            print("  [skip] _extract_state_from_prompt: pattern not found (may already be patched)")
        break

# ── 4. AGENT CELL (id: agent_code) ────────────────────────────────────
for cell in cells:
    if cell.get("id") == "agent_code":
        cell["source"] = [
            "class BoTAgent:\n",
            "    def __init__(self, llm_client, buffer_manager, use_history=True, history_window=3):\n",
            "        self.llm = llm_client\n",
            "        self.buffer_manager = buffer_manager\n",
            "        self.use_history = use_history\n",
            "        self.history_window = history_window\n",
            "        self.memory = []\n",
            "        self.action_log = []\n",
            "\n",
            "    @staticmethod\n",
            "    def _parse_action(response_text):\n",
            "        action = response_text.strip().lower()\n",
            '        if "forward" in action:\n',
            '            return "forward"\n',
            '        if "left" in action:\n',
            '            return "turn_left"\n',
            '        if "right" in action:\n',
            '            return "turn_right"\n',
            '        if "toggle" in action:\n',
            '            return "toggle"\n',
            '        if "pickup" in action:\n',
            '            return "pickup"\n',
            '        if "drop" in action:\n',
            '            return "drop"\n',
            '        return "forward"\n',
            "\n",
            "    def act(self, observation):\n",
            "        distilled = ProblemDistiller.distill(observation)\n",
            "        aid = self.buffer_manager.get_reasoning_aid(distilled)\n",
            "\n",
            '        system_prompt = "You are a MiniGrid navigation agent. Choose exactly one action token: forward, turn_left, turn_right, toggle, pickup, drop."\n',
            "        history_context = self.memory[-self.history_window:] if self.use_history else []\n",
            "        user_prompt = (\n",
            '            f"Current Obs: {observation}\\n"\n',
            '            f"{aid}\\n"\n',
            '            f"Recent history: {history_context}\\n"\n',
            '            "Return only one action token."\n',
            "        )\n",
            "\n",
            "        response, tokens, latency = self.llm.query(system_prompt, user_prompt)\n",
            "        action = self._parse_action(response)\n",
            "\n",
            "        self.memory.append((observation, action))\n",
            '        self.action_log.append({"raw_llm_output": response, "parsed_action": action, "observation": observation})\n',
            "        return action\n",
        ]
        cell["outputs"] = []
        break

# ── 5. RUNNER CELL (id: runner_code) — Bugs 1, 2, 3 ──────────────────
for cell in cells:
    if cell.get("id") == "runner_code":
        cell["source"] = [
            "def _run_single_episode(env, agent, max_steps):\n",
            "    obs = env.reset()\n",
            "    done = False\n",
            "    steps = 0\n",
            "    total_reward = 0.0\n",
            "\n",
            "    while not done and steps < max_steps:\n",
            "        action = agent.act(obs)\n",
            "        obs, reward, done, info = env.step(action)\n",
            "        total_reward += reward\n",
            "        steps += 1\n",
            "\n",
            "    success = total_reward > 0\n",
            "    return success, steps, total_reward\n",
            "\n",
            "\n",
            "def _build_episode_row(\n",
            "    env_id,\n",
            "    episode,\n",
            "    policy,\n",
            "    use_history,\n",
            "    history_window,\n",
            "    max_steps,\n",
            "    model_name,\n",
            "    mock,\n",
            "    success,\n",
            "    steps,\n",
            "    reward,\n",
            "    tokens,\n",
            "    latency,\n",
            "    buffer_size,\n",
            "):\n",
            "    return {\n",
            '        "env": env_id,\n',
            '        "episode": episode,\n',
            '        "policy": policy,\n',
            '        "use_history": use_history,\n',
            '        "history_window": history_window if use_history else 0,\n',
            '        "max_steps": max_steps,\n',
            '        "model": model_name,\n',
            '        "mock": mock,\n',
            '        "buffer_size": buffer_size,\n',
            '        "success": success,\n',
            '        "steps": steps,\n',
            '        "reward": reward,\n',
            '        "tokens": tokens,\n',
            '        "time": latency,\n',
            "    }\n",
            "\n",
            "\n",
            # Bug 1: accept llm_client directly (pre-loaded), plus max_new_tokens/temperature
            # Bug 2: llm is passed in, not created here
            # Bug 3: per-episode deltas for tokens/time
            "def run_experiment(\n",
            "    env_id,\n",
            "    llm_client,\n",
            "    n_episodes=10,\n",
            "    max_steps=100,\n",
            "    use_history=True,\n",
            "    history_window=3,\n",
            "    policy_label=None,\n",
            "    buffer_size=2,\n",
            "):\n",
            "    results = []\n",
            "    all_action_logs = []\n",
            "    buffer_mgr = BufferManager(buffer_size=buffer_size)\n",
            "    env = MinigridTextWrapper(env_id)\n",
            "\n",
            '    policy = policy_label or ("history" if use_history else "reactive")\n',
            "    print(\n",
            '        f"Running {n_episodes} episodes on {env_id} | policy={policy} | "\n',
            '        f"max_steps={max_steps} | model={llm_client.model_name} | mock={llm_client.mock} | buffer_size={buffer_size}"\n',
            "    )\n",
            "\n",
            "    for i in range(n_episodes):\n",
            "        agent = BoTAgent(\n",
            "            llm_client,\n",
            "            buffer_mgr,\n",
            "            use_history=use_history,\n",
            "            history_window=history_window,\n",
            "        )\n",
            "\n",
            "        tokens_before = llm_client.total_tokens\n",
            "        latency_before = llm_client.total_latency\n",
            "\n",
            "        success, steps, total_reward = _run_single_episode(\n",
            "            env=env,\n",
            "            agent=agent,\n",
            "            max_steps=max_steps,\n",
            "        )\n",
            "\n",
            "        ep_tokens = llm_client.total_tokens - tokens_before\n",
            "        ep_latency = llm_client.total_latency - latency_before\n",
            "\n",
            "        for step_idx, log_entry in enumerate(agent.action_log):\n",
            '            log_entry["env"] = env_id\n',
            '            log_entry["episode"] = i\n',
            '            log_entry["step"] = step_idx\n',
            '            log_entry["model"] = llm_client.model_name\n',
            '            log_entry["buffer_size"] = buffer_size\n',
            "        all_action_logs.extend(agent.action_log)\n",
            "\n",
            "        results.append(\n",
            "            _build_episode_row(\n",
            "                env_id=env_id,\n",
            "                episode=i,\n",
            "                policy=policy,\n",
            "                use_history=use_history,\n",
            "                history_window=history_window,\n",
            "                max_steps=max_steps,\n",
            "                model_name=llm_client.model_name,\n",
            "                mock=llm_client.mock,\n",
            "                success=success,\n",
            "                steps=steps,\n",
            "                reward=total_reward,\n",
            "                tokens=ep_tokens,\n",
            "                latency=ep_latency,\n",
            "                buffer_size=buffer_size,\n",
            "            )\n",
            "        )\n",
            '        print(f"  Ep {i}: Success={success}, Steps={steps}, Reward={total_reward:.3f}")\n',
            "\n",
            "    return pd.DataFrame(results), pd.DataFrame(all_action_logs)\n",
            "\n",
            "\n",
            "def _resolve_env_id(candidates):\n",
            '    """Return the first available env_id from a candidate list."""\n',
            "    for env_id in candidates:\n",
            "        try:\n",
            "            test_env = gym.make(env_id)\n",
            "            test_env.close()\n",
            "            return env_id\n",
            "        except Exception:\n",
            "            continue\n",
            "    return None\n",
            "\n",
            "\n",
            "def _default_env_candidate_map():\n",
            "    return {\n",
            '        "MiniGrid-LavaGapS7-v0": ["MiniGrid-LavaGapS7-v0"],\n',
            '        "MiniGrid-BlockedUnlockPickup-v0": [\n',
            '            "MiniGrid-BlockedUnlockPickup-v0",\n',
            '            "MiniGrid-UnlockPickup-v0",\n',
            "        ],\n",
            '        "MiniGrid-DoorKey-5x5-v0": ["MiniGrid-DoorKey-5x5-v0"],\n',
            '        "MiniGrid-Empty-8x8-v0": ["MiniGrid-Empty-8x8-v0"],\n',
            "    }\n",
            "\n",
            "\n",
            "def _resolve_environment_pairs(environments, env_candidate_map=None):\n",
            "    env_candidate_map = env_candidate_map or _default_env_candidate_map()\n",
            "    resolved_envs = []\n",
            "\n",
            "    for env_name in environments:\n",
            "        candidates = env_candidate_map.get(env_name, [env_name])\n",
            "        resolved = _resolve_env_id(candidates)\n",
            "        if resolved is None:\n",
            '            print(f"Skipping {env_name}: no available env id from {candidates}")\n',
            "            continue\n",
            "        resolved_envs.append((env_name, resolved))\n",
            "\n",
            "    return resolved_envs\n",
            "\n",
            "\n",
            "def _empty_errors_df():\n",
            "    return pd.DataFrame(\n",
            '        columns=["model", "env", "resolved_env", "n_episodes_setting", "max_steps", "buffer_size", "history_window", "error"]\n',
            "    )\n",
            "\n",
            "\n",
            "def _build_summary_frame(all_results):\n",
            "    if all_results.empty:\n",
            "        return pd.DataFrame(\n",
            '            columns=["model", "env", "n_episodes_setting", "max_steps", "buffer_size", "history_window", "success", "steps", "reward", "tokens", "time"]\n',
            "        )\n",
            "\n",
            "    return all_results.groupby(\n",
            '        ["model", "env", "n_episodes_setting", "max_steps", "buffer_size", "history_window"], as_index=False\n',
            '    )[["success", "steps", "reward", "tokens", "time"]].mean()\n',
            "\n",
            "\n",
            "def _run_single_condition(\n",
            "    llm_client,\n",
            "    canonical_name,\n",
            "    resolved_env_id,\n",
            "    n_episodes,\n",
            "    max_steps,\n",
            "    history_window,\n",
            "    policy_label,\n",
            "    buffer_size,\n",
            "):\n",
            "    try:\n",
            "        df, action_logs = run_experiment(\n",
            "            env_id=resolved_env_id,\n",
            "            llm_client=llm_client,\n",
            "            n_episodes=n_episodes,\n",
            "            max_steps=max_steps,\n",
            "            use_history=True,\n",
            "            history_window=history_window,\n",
            "            policy_label=policy_label,\n",
            "            buffer_size=buffer_size,\n",
            "        )\n",
            '        df["env"] = canonical_name\n',
            '        df["resolved_env"] = resolved_env_id\n',
            '        df["n_episodes_setting"] = int(n_episodes)\n',
            "        return df, action_logs, None\n",
            "    except Exception as e:\n",
            "        error_row = {\n",
            '            "model": llm_client.model_name,\n',
            '            "env": canonical_name,\n',
            '            "resolved_env": resolved_env_id,\n',
            '            "n_episodes_setting": int(n_episodes),\n',
            '            "max_steps": int(max_steps),\n',
            '            "buffer_size": int(buffer_size),\n',
            '            "history_window": int(history_window),\n',
            '            "error": str(e),\n',
            "        }\n",
            "        return None, None, error_row\n",
            "\n",
            "\n",
            "def build_run_config(\n",
            "    model_candidates,\n",
            "    mock_mode,\n",
            "    max_new_tokens,\n",
            "    temperature,\n",
            "    history_windows,\n",
            "    environments,\n",
            "    n_episodes_list,\n",
            "    max_steps_list,\n",
            "    buffer_sizes,\n",
            "):\n",
            "    return {\n",
            '        "model_candidates": list(model_candidates),\n',
            '        "mock_mode": bool(mock_mode),\n',
            '        "max_new_tokens": int(max_new_tokens),\n',
            '        "temperature": float(temperature),\n',
            '        "history_windows": list(history_windows),\n',
            '        "environments": list(environments),\n',
            '        "n_episodes_list": list(n_episodes_list),\n',
            '        "max_steps_list": list(max_steps_list),\n',
            '        "buffer_sizes": list(buffer_sizes),\n',
            "    }\n",
            "\n",
            "\n",
            "def run_bot_experiments(\n",
            "    model_names,\n",
            "    environments,\n",
            "    n_episodes_list,\n",
            "    max_steps_list,\n",
            "    buffer_sizes=(2,),\n",
            "    history_windows=(3,),\n",
            "    mock=True,\n",
            "    max_new_tokens=16,\n",
            "    temperature=0.0,\n",
            "    return_errors=False,\n",
            "):\n",
            "    resolved_envs = _resolve_environment_pairs(environments)\n",
            "\n",
            "    frames = []\n",
            "    all_action_logs = []\n",
            "    errors = []\n",
            "\n",
            "    total_runs = len(model_names) * len(resolved_envs) * len(n_episodes_list) * len(max_steps_list) * len(buffer_sizes) * len(history_windows)\n",
            "    current_run = 0\n",
            "\n",
            "    for model_name in model_names:\n",
            "        llm_client = LLMClient(\n",
            "            model_name=model_name,\n",
            "            max_new_tokens=max_new_tokens,\n",
            "            temperature=temperature,\n",
            "            mock=mock,\n",
            "        )\n",
            "\n",
            "        for canonical_name, resolved_env_id in resolved_envs:\n",
            "            for n_episodes in n_episodes_list:\n",
            "                for max_steps in max_steps_list:\n",
            "                    for buffer_size in buffer_sizes:\n",
            "                        for history_window in history_windows:\n",
            '                            policy_label = f"BoT_buf{buffer_size}_k{history_window}"\n',
            "                            current_run += 1\n",
            "                            print(\n",
            '                                f"\\n[{current_run}/{total_runs}] {model_name} | {canonical_name} "\n',
            '                                f"| n_ep={n_episodes} | max_steps={max_steps} | buf={buffer_size} | hw={history_window}"\n',
            "                            )\n",
            "\n",
            "                            condition_df, action_logs, error_row = _run_single_condition(\n",
            "                                llm_client=llm_client,\n",
            "                                canonical_name=canonical_name,\n",
            "                                resolved_env_id=resolved_env_id,\n",
            "                                n_episodes=n_episodes,\n",
            "                                max_steps=max_steps,\n",
            "                                history_window=history_window,\n",
            "                                policy_label=policy_label,\n",
            "                                buffer_size=buffer_size,\n",
            "                            )\n",
            "\n",
            "                            if condition_df is not None:\n",
            "                                frames.append(condition_df)\n",
            "                            if action_logs is not None and not action_logs.empty:\n",
            "                                all_action_logs.append(action_logs)\n",
            "                            if error_row is not None:\n",
            "                                errors.append(error_row)\n",
            "                                print(f\"Error: {error_row['error']}\")\n",
            "\n",
            '    all_results = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()\n',
            '    combined_action_logs = pd.concat(all_action_logs, ignore_index=True) if all_action_logs else pd.DataFrame()\n',
            "    errors_df = pd.DataFrame(errors) if errors else _empty_errors_df()\n",
            "\n",
            "    if return_errors:\n",
            "        return all_results, combined_action_logs, errors_df\n",
            "    return all_results, combined_action_logs\n",
            "\n",
            "\n",
            "def save_run_outputs(\n",
            "    all_results,\n",
            "    action_logs=None,\n",
            "    run_errors=None,\n",
            '    output_root="CS 228/outputs",\n',
            '    run_tag="bot_sweep",\n',
            "    config=None,\n",
            "):\n",
            '    """Minimal structured save: episodes/summary/actions/errors + config/metadata."""\n',
            "    run_id = f\"{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}_{run_tag}\"\n",
            "    run_dir = Path(output_root) / run_id\n",
            "    run_dir.mkdir(parents=True, exist_ok=True)\n",
            "\n",
            '    episodes_path = run_dir / "episodes.csv"\n',
            '    summary_path = run_dir / "summary.csv"\n',
            '    actions_path = run_dir / "actions.csv"\n',
            '    errors_path = run_dir / "errors.csv"\n',
            '    config_path = run_dir / "config.json"\n',
            '    metadata_path = run_dir / "metadata.json"\n',
            "\n",
            "    all_results.to_csv(episodes_path, index=False)\n",
            "    summary = _build_summary_frame(all_results)\n",
            "    summary.to_csv(summary_path, index=False)\n",
            "\n",
            "    if action_logs is not None and not action_logs.empty:\n",
            "        action_logs.to_csv(actions_path, index=False)\n",
            "\n",
            "    if run_errors is None:\n",
            "        run_errors = _empty_errors_df()\n",
            "    run_errors.to_csv(errors_path, index=False)\n",
            "\n",
            "    if config is None:\n",
            "        config = {}\n",
            '    with config_path.open("w", encoding="utf-8") as f:\n',
            "        json.dump(config, f, indent=2)\n",
            "\n",
            "    metadata = {\n",
            '        "run_id": run_id,\n',
            '        "saved_at": datetime.now(timezone.utc).isoformat(),\n',
            '        "rows": int(len(all_results)),\n',
            '        "action_log_rows": int(len(action_logs)) if action_logs is not None else 0,\n',
            '        "errors": int(len(run_errors)),\n',
            "    }\n",
            '    with metadata_path.open("w", encoding="utf-8") as f:\n',
            "        json.dump(metadata, f, indent=2)\n",
            "\n",
            "    return {\n",
            '        "run_id": run_id,\n',
            '        "run_dir": str(run_dir),\n',
            '        "episodes_path": str(episodes_path),\n',
            '        "summary_path": str(summary_path),\n',
            '        "actions_path": str(actions_path),\n',
            '        "errors_path": str(errors_path),\n',
            '        "config_path": str(config_path),\n',
            '        "metadata_path": str(metadata_path),\n',
            "    }\n",
        ]
        cell["outputs"] = []
        break

# ── 6. EXECUTE CELL (id: execute_code) — Bug 1 passthrough ───────────
for cell in cells:
    if cell.get("id") == "execute_code":
        cell["source"] = [
            "all_results, action_logs, run_errors = run_bot_experiments(\n",
            "    model_names=MODEL_CANDIDATES,\n",
            "    environments=ENVIRONMENTS,\n",
            "    n_episodes_list=N_EPISODES_LIST,\n",
            "    max_steps_list=MAX_STEPS_LIST,\n",
            "    buffer_sizes=BUFFER_SIZES,\n",
            "    history_windows=HISTORY_WINDOWS,\n",
            "    mock=MOCK_MODE,\n",
            "    max_new_tokens=MAX_NEW_TOKENS,\n",
            "    temperature=TEMPERATURE,\n",
            "    return_errors=True,\n",
            ")\n",
            "\n",
            "run_config = build_run_config(\n",
            "    model_candidates=MODEL_CANDIDATES,\n",
            "    mock_mode=MOCK_MODE,\n",
            "    max_new_tokens=MAX_NEW_TOKENS,\n",
            "    temperature=TEMPERATURE,\n",
            "    history_windows=HISTORY_WINDOWS,\n",
            "    environments=ENVIRONMENTS,\n",
            "    n_episodes_list=N_EPISODES_LIST,\n",
            "    max_steps_list=MAX_STEPS_LIST,\n",
            "    buffer_sizes=BUFFER_SIZES,\n",
            ")\n",
            "\n",
            "run_artifacts = save_run_outputs(\n",
            "    all_results=all_results,\n",
            "    action_logs=action_logs,\n",
            "    run_errors=run_errors,\n",
            "    output_root=OUTPUT_ROOT,\n",
            "    run_tag=RUN_TAG,\n",
            "    config=run_config,\n",
            ")\n",
            "\n",
            'print("\\nExperiment Results Summary")\n',
            'print(f"Rows: {len(all_results)}")\n',
            'print(f"Action log rows: {len(action_logs)}")\n',
            'print(f"Errors: {len(run_errors)}")\n',
            "print(f\"Saved to: {run_artifacts['run_dir']}\")\n",
            "\n",
            "display(all_results.head(10))\n",
            "if not run_errors.empty:\n",
            "    display(run_errors.head(10))\n",
        ]
        cell["outputs"] = []
        break

# ── 8. VIZ CELL (id: viz_code) — 5 plots ─────────────────────────────
for cell in cells:
    if cell.get("id") == "viz_code":
        cell["source"] = [
            'if "all_results" not in dir() or all_results.empty:\n',
            '    print("No experiment results available to visualize.")\n',
            "else:\n",
            "    df = all_results.copy()\n",
            '    env_short = df["env"].str.replace("MiniGrid-", "").str.replace("-v0", "")\n',
            '    df["env_short"] = env_short\n',
            "\n",
            "    fig, axes = plt.subplots(2, 3, figsize=(22, 12))\n",
            "\n",
            "    # ── Plot 1: Model Comparison (top-left) ──\n",
            '    model_env = df.groupby(["env_short", "model"])["success"].mean().unstack(fill_value=0)\n',
            '    model_env.plot(kind="bar", ax=axes[0, 0], colormap="Set2")\n',
            '    axes[0, 0].set_title("Success Rate: 3B vs 7B", fontweight="bold")\n',
            '    axes[0, 0].set_ylabel("Success Rate")\n',
            '    axes[0, 0].set_xlabel("")\n',
            "    axes[0, 0].set_ylim(0, 1)\n",
            "    axes[0, 0].tick_params(axis='x', rotation=30)\n",
            "    axes[0, 0].legend(title='Model', fontsize=8)\n",
            "\n",
            "    # ── Plot 2: Buffer Size Effect (top-center) ──\n",
            '    buf_env = df.groupby(["env_short", "buffer_size"])["success"].mean().unstack(fill_value=0)\n',
            '    buf_env.columns = [f"buf={int(c)}" for c in buf_env.columns]\n',
            '    buf_env.plot(kind="bar", ax=axes[0, 1], colormap="Paired")\n',
            '    axes[0, 1].set_title("Success Rate: Buffer Size 2 vs 5", fontweight="bold")\n',
            '    axes[0, 1].set_ylabel("Success Rate")\n',
            '    axes[0, 1].set_xlabel("")\n',
            "    axes[0, 1].set_ylim(0, 1)\n",
            "    axes[0, 1].tick_params(axis='x', rotation=30)\n",
            "    axes[0, 1].legend(title='Templates', fontsize=8)\n",
            "\n",
            "    # ── Plot 3: History Window Effect (top-right) ──\n",
            '    hw_env = df.groupby(["history_window", "env_short"])["success"].mean().unstack(fill_value=0)\n',
            '    hw_env.plot(kind="line", marker="o", ax=axes[0, 2], linewidth=2)\n',
            '    axes[0, 2].set_title("Success Rate vs History Window", fontweight="bold")\n',
            '    axes[0, 2].set_xlabel("History Window")\n',
            '    axes[0, 2].set_ylabel("Success Rate")\n',
            "    axes[0, 2].set_ylim(0, 1)\n",
            "    axes[0, 2].set_xticks(sorted(df['history_window'].unique()))\n",
            "    axes[0, 2].legend(title='Env', fontsize=7)\n",
            "\n",
            "    # ── Plot 4: Config Heatmap (bottom-left) ──\n",
            '    df["config"] = (\n',
            '        df["model"].str.split("/").str[-1].str.replace("Qwen2.5-", "") + "\\n"\n',
            '        + "buf=" + df["buffer_size"].astype(str)\n',
            '        + " k=" + df["history_window"].astype(str)\n',
            "    )\n",
            '    heat_data = df.groupby(["env_short", "config"])["success"].mean().unstack(fill_value=0)\n',
            "    sns.heatmap(\n",
            "        heat_data,\n",
            "        annot=True,\n",
            '        fmt=".2f",\n',
            '        cmap="YlGn",\n',
            "        vmin=0,\n",
            "        vmax=1,\n",
            "        ax=axes[1, 0],\n",
            "        cbar_kws={'label': 'Success Rate'},\n",
            "    )\n",
            '    axes[1, 0].set_title("Success Rate Heatmap (all configs)", fontweight="bold")\n',
            '    axes[1, 0].set_ylabel("Environment")\n',
            '    axes[1, 0].set_xlabel("Config")\n',
            "    axes[1, 0].tick_params(axis='x', rotation=45, labelsize=7)\n",
            "    axes[1, 0].tick_params(axis='y', rotation=0)\n",
            "\n",
            "    # ── Plot 5: Steps Distribution (bottom-center) ──\n",
            '    model_short = df["model"].str.split("/").str[-1]\n',
            "    sns.boxplot(\n",
            '        data=df.assign(model_short=model_short),\n',
            '        x="env_short",\n',
            '        y="steps",\n',
            '        hue="model_short",\n',
            "        ax=axes[1, 1],\n",
            '        palette="Set2",\n',
            "    )\n",
            '    axes[1, 1].set_title("Steps Distribution by Env & Model", fontweight="bold")\n',
            '    axes[1, 1].set_xlabel("")\n',
            '    axes[1, 1].set_ylabel("Steps")\n',
            "    axes[1, 1].tick_params(axis='x', rotation=30)\n",
            "    axes[1, 1].legend(title='Model', fontsize=8)\n",
            "\n",
            "    # ── Plot 6: Reward by Config (bottom-right) ──\n",
            '    reward_data = df.groupby(["env_short", "buffer_size"])["reward"].mean().unstack(fill_value=0)\n',
            '    reward_data.columns = [f"buf={int(c)}" for c in reward_data.columns]\n',
            '    reward_data.plot(kind="bar", ax=axes[1, 2], colormap="coolwarm")\n',
            '    axes[1, 2].set_title("Average Reward by Env & Buffer Size", fontweight="bold")\n',
            '    axes[1, 2].set_ylabel("Reward")\n',
            '    axes[1, 2].set_xlabel("")\n',
            "    axes[1, 2].tick_params(axis='x', rotation=30)\n",
            "    axes[1, 2].legend(title='Templates', fontsize=8)\n",
            "\n",
            "    plt.tight_layout()\n",
            "\n",
            '    artifacts = globals().get("run_artifacts")\n',
            "    if artifacts:\n",
            '        out_path = Path(artifacts["run_dir"]) / "overview.png"\n',
            "        fig.savefig(out_path, dpi=150, bbox_inches='tight')\n",
            '        print(f"Saved plot to: {out_path}")\n',
            "\n",
            "    plt.show()\n",
            "\n",
            "    # ── Summary Table ──\n",
            '    print("\\nDetailed Summary:")\n',
            '    summary = df.groupby(["model", "env", "buffer_size", "history_window"])[\n',
            '        ["success", "steps", "reward", "tokens", "time"]\n',
            "    ].mean()\n",
            "    display(summary)\n",
        ]
        cell["outputs"] = []
        break

with open(nb_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print("Done. All 6 bug fixes applied to bot_exploration_3b.ipynb")
print()
print("Fixes applied:")
print("  1. MAX_NEW_TOKENS/TEMPERATURE now passed through config -> run_bot_experiments -> LLMClient")
print("  2. LLM loaded once per model in outer loop, reused across all conditions")
print("  3. tokens/time are per-episode deltas, not cumulative totals")
print("  4. get_text_obs scans full grid for keys, doors, boxes, balls, lava")
print("  5. Envs with no goal tile fall back to box/ball as target")
print("  6. Viz cell groups by buffer_size, shows buf=2 vs buf=5 comparison")
